spring:
  datasource:
    url: jdbc:mysql://localhost:3307/examplesdb?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: nadaa
    password: nadaa1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


